### ISSUE TITLE
thinkpad-dock-hook crashes 

### ISSUE THREAD

**Issue by kasbah** [martin-ueding/thinkpad-scripts#110] opened 2015-10-15 11:12 UTC
When I startup I get a notification from Unity with "System program problem detected". There is a new log `/var/crash/_usr_bin_thinkpad-dock-hook.0.crash` which says at the bottom:

~~~
PythonArgs: ['/usr/bin/thinkpad-dock-hook', 'off']
Traceback:
 Traceback (most recent call last):
   File "/usr/lib/python3.4/logging/handlers.py", line 819, in _connect_unixsocket
     self.socket.connect(address)
 FileNotFoundError: [Errno 2] No such file or directory
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/bin/thinkpad-dock-hook", line 9, in <module>
     load_entry_point('thinkpad-scripts==4.1.5', 'console_scripts', 'thinkpad-dock-hook')()
   File "/usr/lib/python3/dist-packages/tps/hooks.py", line 126, in main_dock_hook
     tps.config.set_up_logging(options.verbose)
   File "/usr/lib/python3/dist-packages/tps/config.py", line 205, in set_up_logging
     syslog = logging.handlers.SysLogHandler(address='/dev/log')
   File "/usr/lib/python3.4/logging/handlers.py", line 802, in __init__
     self._connect_unixsocket(address)
   File "/usr/lib/python3.4/logging/handlers.py", line 830, in _connect_unixsocket
     self.socket.connect(address)
 FileNotFoundError: [Errno 2] No such file or directory
UserGroups: 
~~~

I don't own a dock. How do I disable the dock functionality all together?

**Comment by martin-ueding** [comment] 2015-10-15 17:23
I guess you are on Ubuntu Trusty and use the version form my PPA? That would explain why you have version 4.1.5. But that is not the matter here.

If you look at [the line](https://github.com/martin-ueding/thinkpad-scripts/blob/v4.1.5/tps/config.py#L205) that is flagged in the traceback you can see that it is the log device. For some reason I [set the path to a fixed device](https://github.com/martin-ueding/thinkpad-scripts/commit/300bcb6dcd140c79fa497160a2c8a4590e118ab7). There must be some reason for that, I just cannot remember why I did that. This might explain some irregularities in other issues where there is no output in the syslog.

@jturner314, do you know why this absolute path was added?

From the [Python documentation](https://docs.python.org/3/library/logging.handlers.html#sysloghandler) it looks like that `/dev/log` is the standard device on Linux, so it should be just fine with Ubuntu.

I am also not sure why the dock hook is called on your machine when you start up. One easy solution would be to delete the file `/usr/bin/thinkpad-dock-hook`. When you reinstall the package, it will be created again, though.

I could add a `dock-hook.disable` option (or something similar) to the configuration file to disable the hook. This would require you to update your version of thinkpad scripts then and I am not sure whether Ubuntu Trusty already had sufficient dependencies. There was some problem when we required some specific version of `udev` I think. I would need to check that before I backport the package to Ubuntu Trusty.

**Comment by jturner314** [comment] 2015-10-16 05:12
### `thinkpad-dock` getting called during boot

I'm also seeing `thinkpad-dock` being called during boot. It occurs early in the boot sequence, even before my partitions (`/home`, `/var`, etc.) are mounted. Looking at my historical logs, it appears that this behavior started after I upgraded some packages on 2015-06-22, most notably `libsystemd` and `systemd` (which contain `udev`) from version `219-6` to `221-1`. I don't think it does any harm, but I can see how this would be annoying in Ubuntu with that system error popup dialog.

I don't see an easy way to ignore the hook only during boot, but if this becomes a problem, we can come up with something. I do think it would be a good idea to add a configuration option to completely disable the hook, as you suggested.

### Logging address/path

I assume that `config.py` uses the absolute path `/dev/log` because Python's default is to use UDP port 514 to communicate with the syslog daemon on localhost, which may or may not work. The docs say:

> Note that if your server is not listening on UDP port 514, SysLogHandler may appear not to work. In that case, check what address you should be using for a domain socket - it’s system dependent. For example, on Linux it’s usually ‘/dev/log’ but on OS/X it’s ‘/var/run/syslog’. You’ll need to check your platform and use the appropriate address (you may need to do this check at runtime if your application needs to run on several platforms). On Windows, you pretty much have to use the UDP option.

For example, that port is closed on my laptop. You can check the status of that port on your computer with
```shell
sudo nmap -sU -p514 localhost
```

An improvement would be to use `/dev/log` only if it exists and fall back onto UDP port 514 on localhost when `/dev/log` does not exist.

**Comment by martin-ueding** [comment] 2015-10-16 07:33
I just checked on my device, that port is closed too. Perhaps because I have set the firewall to block almost everything? It would explain that I have changed the path such that it would work on my machine.

The crash is caused by the logging at the present moment. If that is caused by the early call on startup, it might be caused because it is called before syslog is even there. I will implement a check that uses `/dev/log` in case it is there. If the UDP version does not work, I'll catch the exception and just do not log to syslog. I am not sure whether that is a bad idea. A configuration option could be added to let theprogram crash right there?

If the hook is called way too early, this might not really help. Other programs will not be able to do something useful. Perhaps we add a minimum uptime limit such that `uptime` has to give at least something like two minutes before the hook is applied? I'd make it a configuration option such that a user with SSD can reduce that limit. That of course is just a hack since race conditions cannot be cured with timeouts. On the other hand it feels like a huge can of worms with systemd which (as an Ubuntu user) is nothing I have much experience with.

**Comment by martin-ueding** [comment] 2015-10-16 08:09
I now added those things. In the Debian package I saw the requirement `udev (>= 196)`. Looking at the [Ubuntu package index](http://packages.ubuntu.com/trusty/udev) I could see that Trusty comes with `udev` in version 204 such that should be satisfied. That should be the only problem with backporting those things. Now I will just quickly test whether the current `develop` branch runs on Ubuntu Trusty in a virtual machine. There I cannot rotate the screen, but I can see whether the Debian package would install.

**Comment by martin-ueding** [comment] 2015-10-16 08:23
I could successfully build the package on Ubuntu Trusty and install it. I do not see a problem with that right away …

In order to make it easiest for you I uploaded the backport to my PPA. In perhaps half an hour or hour you should be able to get the new package through a simple upgrade if you use my PPA.

**Comment by jturner314** [comment] 2015-10-20 01:09
> Perhaps because I have set the firewall to block almost everything?

That's unlikely because in most configurations (e.g. the default Ubuntu UFW configuration), the firewall doesn't filter localhost. (It usually only filters requests to/from other computers.) Also, the `nmap` docs say:

> The state is either open, filtered, closed, or unfiltered.  Open.  means that an application on the target machine is listening for connections/packets on that port.  Filtered.  means that a firewall, filter, or other network obstacle is blocking the port so that Nmap cannot tell whether it is open or closed.  Closed.  ports have no application listening on them, though they could open up at any time. Ports are classified as unfiltered.  when they are responsive to Nmap's probes, but Nmap cannot determine whether they are open or closed. Nmap reports the state combinations open|filtered.  and closed|filtered.  when it cannot determine which of the two states describe a port.

My guess is that you simply don't have your logging daemon configured to listen on that port (which is the case for my computer).

> ...it might be caused because it is called before syslog is even there.

I don't think that's the case on my computer because I am seeing entries in the log before then, but it may be true on non-systemd systems (such as Ubuntu systems before 15.04). The `logger` man page hints at something like this:

> --socket-errors[=mode]
Print errors about Unix socket connections.  The mode can be a value of off, on, or auto.  When the mode is auto logger will detect if the init process is systemd, and if so assumption is made  /dev/log  can  be  used early  at  boot.   Other  init  systems  lack  of  /dev/log will not cause errors that is identical with messaging using openlog(3) system call.

Your implementation in v4.7.0 (falling back to UDP when `/dev/log` is not available) looks good to me.

> Perhaps we add a minimum uptime limit such that uptime has to give at least something like two minutes before the hook is applied?

What do you think of something like #111 instead?

**Comment by martin-ueding** [comment] 2015-10-20 15:18
With version 4.7.1 that encorporates #111, this should be fixed. Could you please test it? It is built and uploaded to the Ubuntu PPA for 15.04 right now. I'll also do a backport to 14.04.

**Comment by kasbah** [comment] 2015-10-24 22:02
Seems fine for me now. :+1:

**Comment by martin-ueding** [comment] 2015-10-25 14:11
Okay, I'll close that issue then.

**Closed by martin-ueding** 2015-10-25 14:11 UTC
